### PR TITLE
add appveyor

### PR DESCRIPTION
**Pull request by vincenthz**

### CODE REVIEW

**Comment by harendra-kumar** [comment]
ha ha...I too added an appveyor PR just now.

**Comment by harendra-kumar** [comment]
You can drop this one and merge mine as it does a few more useful things, for example it tests from sdist to make sure the distribution is good to go. Here is the script I use and more details about it: https://github.com/harendra-kumar/package-test

**Comment by vincenthz** [comment]
ha ! the coicidence. are you behind me or something ? ;)

happy to drop it, I've copied the .yml from foundation, your .yml looks a bit more elaborate indeed.

**Comment by harendra-kumar** [comment]
I added code to get context switch stats using `getrusage` and wanted to check if it works on mingw as well, appveyor was needed because I do not have a windows machine.

The same script works for appveyor and travis, but the travis stuff is already working so I did not change that. It can report coverage as well to coveralls.io. I can set it up if you like, will take 5 min.

**Comment by vincenthz** [comment]
I was changing some windows code path too; I've got a windows machine for testing, but I prefer doing change on unix and having a safety net like appveyor :)

**Pull request closed without merging**
