### PR TITLE
export runBenchmarkable' from Gauge.Benchmark

### PR DESCRIPTION
**Pull request by runeksvendsen**
Under the **Future Feature Plan** section of the README it says: _"Make the library more useful as a standalone library to gather benchmark numbers related to functions in a programatic way"_. This PR seeks to improve gauge in this regard.

My use case is that I want to write a performance test which asserts that some algorithm, applied to some input data, runs within some specified upper time bound.

### CODE REVIEW

**Comment by runeksvendsen** [comment]
Another option would be to create a new module, e.g. `Gauge.Standalone`, and export `runBenchmarkable'` from there (perhaps renaming it). Thus separating concerns a bit more.

Let me know if you prefer this option, and I will correct the PR.

**Comment by harendra-kumar** [comment]
All the parameters to this function (min duration, min samples, limit) are configurable via `Config` and you can also supply those from command line of the executable produced by gauge. You can use the `--help` CLI option to see all the options. I am wondering if that is sufficient for your use case.

**Comment by runeksvendsen** [comment]
What I'm trying to do is create a test that benchmarks a function and asserts that the median running time is below some upper bound. I imagine using `runBenchmarkable'` like so:

```haskell
import qualified Library as Lib
import Test.Hspec.Expectations (shouldSatisfy, Expectation)
import Gauge.Benchmark (whnf, runBenchmarkable')

acceptableRunningTime :: InputData -> Expectation
acceptableRunningTime input = do
   benchResult <- runBenchmarkable' (whnf Lib.functionToBench input) 20 20 1e9
   benchResult `shouldSatisfy` \res -> meanTimeSeconds res <= 0.5
```

As far as I can see I need something that will run a `Benchmarkable` and produce a value that contains timing statistics -- which `runBenchmarkable'` does. 

However I might be missing something. Is there a way to achieve this without modifying gauge?

**Comment by runeksvendsen** [comment]
I'm trying to use `runBenchmarkable'` as follows:

```haskell
import qualified Gauge.Benchmark as Gauge
import Control.DeepSeq (NFData)


benchSeconds :: NFData a => IO a -> IO Double
benchSeconds io = do
    (_, seconds, count) <- Gauge.runBenchmarkable' (Gauge.nfIO io) 1 1 1e9
    return seconds

main :: IO ()
main = do
    time <- benchSeconds $ do
        print $ sum [0..100000]
        return ()
    print time
```

but running `main` results in a floating point exception (`floating point exception` is printed to the console, without a stack trace). What am I doing wrong here?

I realize that inside `benchSeconds` I should divide `seconds` by `count`, but I refrained from doing so in order to make it clear that I'm not doing anything that could result in division by zero.

**Pull request closed without merging**
