### PR TITLE
add nfAppIO/whnfAppIO

### PR DESCRIPTION
**Pull request by rubenpieters**
Add the `nfAppIO` and `whnfAppIO` functions similar to https://github.com/bos/criterion/pull/199 . I adapted a similar style compared to `pureFunc`, rather than just copying my implementations from the criterion pull request.

### CODE REVIEW

**Comment by harendra-kumar** [comment]
@rubenpieters thanks for the PR and sorry for letting it languish. The code looks good to me. I guess this should fix #76. Is it possible to add a benchmark demonstrating a simple/contrived case where it helps?

I would ideally want to get rid of the `nfIO` and `whnfIO` as they are prone to unpredictable results. But they need to remain for backward compatibility and compatibility with criterion as well. Maybe we can deprecate those?

@vincenthz any thoughts on this PR? Are the API names good or there are any better alternatives?

**Comment by harendra-kumar** [comment]
I just looked at criterion and since this has already been merged in criterion with these names we should keep the names as is for compatibility. We should also merge Ryan's doc changes from https://github.com/bos/criterion/commit/6b94e1a8a34afaed0a226114105a2f2a6a8076c6 .

**Comment by rubenpieters** [comment]
I have an isolated use case where this problem occurs in the following repo: https://github.com/rubenpieters/conduit-bench/tree/with-gauge .

**Comment by harendra-kumar** [comment]
Good work @rubenpieters  and sorry for the delay in merging.

**Pull request merged**
