### PR TITLE
Use the same script for appveyor and travis

### PR DESCRIPTION
**Pull request by harendra-kumar**
The appveyor test is based on https://github.com/harendra-kumar/package-test. I have adapted the travis tests as well to use the same script. This script creates a sdist first and tests the package after unpacking it from sdist. So we are sure that the package is ok to upload to hackage.

This script also has support for "cabal" tests using stack or pure cabal in case we want to build those as well. It also supports sending coverage info to coveralls.io for coverage reporting and badge. We can enable that if required.

Also changed the nightly resolver to lts-10.0 and lts-9 to lts-9.20.

### CODE REVIEW

**Comment by harendra-kumar** [comment]
@vincenthz I am done iterating with this one, can you take a look and merge if it looks ok?

**Comment by harendra-kumar** [comment]
@vincenthz I am merging this, let me know in case you have any comments.

**Comment by vincenthz** [comment]
That looks fine, I just want to add on:

```+  - GHC_OPTIONS="-O0 -Werror"```

Is there a reason for building with -O0 ? faster build ?

And the main thing is, while I like Werror in theory, in practice it often trigger bogus build error specially with multiple GHC support which are normally harmless (e.g. duplicate imports). I do concede that sadly because there's no way to promote selectively the good & important warnings, that usually leave older version at risks.

**Comment by harendra-kumar** [comment]
We can remove the `-O0`. It can be faster and avoid build timeout for huge projects, but for smaller projects it should not matter. 

We could use `-Wno-unused-imports` to disable the unused import warnings but that will also disable the genuine issues. I guess it is ok to do some extra work once in a while. Now that we have cleaned all cases it is mostly about taking care of such issues as we incrementally change code.

**Comment by harendra-kumar** [comment]
I think I got a habit of using `-O0` from my experience in the https://github.com/harendra-kumar/unicode-transforms package, where optimizing a big file took more memory causing the build to hang on travis.

**Pull request merged**
